#version 460
#extension GL_GOOGLE_include_directive : enable
#include "shared.glsl"
#include "shared/spectral.glsl"
#include "matrices.h"
#include "colourspaces.glsl"

layout(local_size_x = DT_LOCAL_SIZE_X, local_size_y = DT_LOCAL_SIZE_Y, local_size_z = 1) in;
layout(std140, set = 0, binding = 1) uniform params_t
{
  int observer;
} params;
layout(set = 1, binding = 0) uniform sampler2D img_spectrum[spectral_groups];
layout(set = 1, binding = 1) uniform writeonly image2D img_out;

shared vec4 shared_cmf_x[spectral_groups];
shared vec4 shared_cmf_y[spectral_groups];
shared vec4 shared_cmf_z[spectral_groups];

void main()
{
  uint tid = gl_LocalInvocationIndex;
  if (tid < spectral_groups)
  {
    int obs = clamp(params.observer, 0, 3);
    shared_cmf_x[tid] = (obs == 1) ? cmf_1964_x[tid] : ((obs == 2) ? cmf_2006_x[tid] : ((obs == 3) ? cmf_2015_10_x[tid] : spectral_cmf_x[tid]));
    shared_cmf_y[tid] = (obs == 1) ? cmf_1964_y[tid] : ((obs == 2) ? cmf_2006_y[tid] : ((obs == 3) ? cmf_2015_10_y[tid] : spectral_cmf_y[tid]));
    shared_cmf_z[tid] = (obs == 1) ? cmf_1964_z[tid] : ((obs == 2) ? cmf_2006_z[tid] : ((obs == 3) ? cmf_2015_10_z[tid] : spectral_cmf_z[tid]));
  }
  barrier();

  ivec2 ipos = ivec2(gl_GlobalInvocationID);
  if(any(greaterThanEqual(ipos, imageSize(img_out)))) return;
  vec3 xyz = vec3(0.0);
  SPECTRAL_LOOP(group)
  {
    vec4 radiance = spectral_fetch(img_spectrum, ipos, group);
    xyz.x += dot(radiance, shared_cmf_x[group]);
    xyz.y += dot(radiance, shared_cmf_y[group]);
    xyz.z += dot(radiance, shared_cmf_z[group]);
  }
  xyz *= spectral_step_nm;
  imageStore(img_out, ipos, vec4(max(XYZ_to_rec2020(xyz), vec3(0.0)), 1.0));
}
